name: Cypress CI (Fast)

on:
  push:
    branches: [ main, dev, staging ]

jobs:
  e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 15            # กันงานค้างเป็นชั่วโมง

    strategy:
      fail-fast: false
      matrix:
        env: [dev]                 # เติม staging ได้: [dev, staging]
    env:
      CI: "1"                      # บอก Cypress ว่าอยู่ใน CI (ไม่เปิด UI)
      ENV: ${{ matrix.env }}       # ส่งต่อให้ config ของคุณเลือก baseUrl เอง
      # หากเว็บคุณมี Basic Auth / token ให้ใส่เป็น Secrets แล้ว mapping มาเป็น env ตรงนี้

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Cache Cypress binary
        uses: actions/cache@v4
        with:
          path: ~/.cache/Cypress
          key: ${{ runner.os }}-cypress-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-cypress-

      - name: Install deps
        run: npm ci

      - name: Verify Cypress
        run: npx cypress verify

      # (ถ้าเว็บต้อง start เอง ให้ใช้ start-server-and-test)
      # - name: Start app and test
      #   run: npx start-server-and-test "npm run start" http://localhost:3000 "npx cypress run --headless --browser electron"

      - name: Run Cypress (headless, fast)
        run: |
          npx cypress run \
            --headless \
            --browser electron \
            --config "video=false,retries=1,pageLoadTimeout=60000,defaultCommandTimeout=8000,watchForFileChanges=false" \
            --reporter dot
        # ถ้าอยากให้รันเฉพาะไฟล์ควันหลง (smoke) ใส่ --spec "cypress/e2e/**/smoke*.cy.*"

      # เปิดไว้สำหรับดีบักเมื่อมี fail (เก็บไฟล์ artifacts)
      - name: Upload screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore

      - name: Upload videos
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos
          if-no-files-found: ignore
